const packBlueprints = {
    "(S)FotR - Starter": "/gemp-lotr/images/boosters/fotr_starter_selection.png",
    "(S)MoM - Starter": "/gemp-lotr/images/boosters/mom_starter_selection.png",
    "(S)RotEL - Starter": "/gemp-lotr/images/boosters/rotel_starter_selection.png",

    "(S)TTT - Starter": "/gemp-lotr/images/boosters/ttt_starter_selection.png",
    "(S)BoHD - Starter": "/gemp-lotr/images/boosters/bohd_starter_selection.png",
    "(S)EoF - Starter": "/gemp-lotr/images/boosters/eof_starter_selection.png",

    "(S)RotK - Starter": "/gemp-lotr/images/boosters/rotk_starter_selection.png",
    "(S)SoG - Starter": "/gemp-lotr/images/boosters/sog_starter_selection.png",
    "(S)MD - Starter": "/gemp-lotr/images/boosters/md_starter_selection.png",

    "(S)SH - Starter": "/gemp-lotr/images/boosters/sh_starter_selection.png",
    "(S)BR - Starter": "/gemp-lotr/images/boosters/br_starter_selection.png",
    "(S)BL - Starter": "/gemp-lotr/images/boosters/bl_starter_selection.png",
    
    "(S)HU - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)RoS - Starter": "/gemp-lotr/images/boosters/starter_selection.png",

    "(S)FotR - Tengwar": "/gemp-lotr/images/boosters/fotr_tengwar_selection.png",
    "(S)TTT - Tengwar": "/gemp-lotr/images/boosters/ttt_tengwar_selection.png",
    "(S)RotK - Tengwar": "/gemp-lotr/images/boosters/rotk_tengwar_selection.png",
    "(S)SH - Tengwar": "/gemp-lotr/images/boosters/sh_tengwar_selection.png",
    "(S)Tengwar": "/gemp-lotr/images/boosters/tengwar_selection.png",
    "Random Tengwar": "/gemp-lotr/images/boosters/random_tengwar.png",

    "(S)All Decipher Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)Movie Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)TS Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",

    "FotR - League Starter": "/gemp-lotr/images/boosters/fotr_league_starter.png",
    "Random FotR Foil Common": "/gemp-lotr/images/boosters/random_foil.png",
    "Random FotR Foil Uncommon": "/gemp-lotr/images/boosters/random_foil.png",

    "FotR - Gandalf Starter": "/gemp-lotr/images/boosters/fotr_gandalf_starter.png",
    "FotR - Aragorn Starter": "/gemp-lotr/images/boosters/fotr_aragorn_starter.png",
    "FotR - Booster": "/gemp-lotr/images/boosters/fotr_booster.png",

    "MoM - Gandalf Starter": "/gemp-lotr/images/boosters/mom_gandalf_starter.png",
    "MoM - Gimli Starter": "/gemp-lotr/images/boosters/mom_gimli_starter.png",
    "MoM - Booster": "/gemp-lotr/images/boosters/mom_booster.png",

    "RotEL - Boromir Starter": "/gemp-lotr/images/boosters/rotel_boromir_starter.png",
    "RotEL - Legolas Starter": "/gemp-lotr/images/boosters/rotel_legolas_starter.png",
    "RotEL - Booster": "/gemp-lotr/images/boosters/rotel_booster.png",

    "TTT - Aragorn Starter": "/gemp-lotr/images/boosters/ttt_aragorn_starter.png",
    "TTT - Theoden Starter": "/gemp-lotr/images/boosters/ttt_theoden_starter.png",
    "TTT - Booster": "/gemp-lotr/images/boosters/ttt_booster.png",

    "BoHD - Eowyn Starter": "/gemp-lotr/images/boosters/bohd_eowyn_starter.png",
    "BoHD - Legolas Starter": "/gemp-lotr/images/boosters/bohd_legolas_starter.png",
    "BoHD - Booster": "/gemp-lotr/images/boosters/bohd_booster.png",

    "EoF - Faramir Starter": "/gemp-lotr/images/boosters/eof_faramir_starter.png",
    "EoF - Witch-king Starter": "/gemp-lotr/images/boosters/eof_witch_king_starter.png",
    "EoF - Booster": "/gemp-lotr/images/boosters/eof_booster.png",

    "RotK - Aragorn Starter": "/gemp-lotr/images/boosters/rotk_aragorn_starter.png",
    "RotK - Eomer Starter": "/gemp-lotr/images/boosters/rotk_eomer_starter.png",
    "RotK - Booster": "/gemp-lotr/images/boosters/rotk_booster.png",

    "SoG - Merry Starter": "/gemp-lotr/images/boosters/sog_merry_starter.png",
    "SoG - Pippin Starter": "/gemp-lotr/images/boosters/sog_pippin_starter.png",
    "SoG - Booster": "/gemp-lotr/images/boosters/sog_booster.png",

    "MD - Frodo Starter": "/gemp-lotr/images/boosters/md_frodo_starter.png",
    "MD - Sam Starter": "/gemp-lotr/images/boosters/md_sam_starter.png",
    "MD - Booster": "/gemp-lotr/images/boosters/md_booster.png",

    "SH - Aragorn Starter": "/gemp-lotr/images/boosters/sh_aragorn_starter.png",
    "SH - Eowyn Starter": "/gemp-lotr/images/boosters/sh_eowyn_starter.png",
    "SH - Gandalf Starter": "/gemp-lotr/images/boosters/sh_gandalf_starter.png",
    "SH - Legolas Starter": "/gemp-lotr/images/boosters/sh_legolas_starter.png",
    "SH - Booster": "/gemp-lotr/images/boosters/sh_booster.png",

    "BR - Mouth Starter": "/gemp-lotr/images/boosters/br_mouth_starter.png",
    "BR - Saruman Starter": "/gemp-lotr/images/boosters/br_saruman_starter.png",
    "BR - Booster": "/gemp-lotr/images/boosters/br_booster.png",

    "BL - Arwen Starter": "/gemp-lotr/images/boosters/bl_arwen_starter.png",
    "BL - Boromir Starter": "/gemp-lotr/images/boosters/bl_boromir_starter.png",
    "BL - Booster": "/gemp-lotr/images/boosters/bl_booster.png",

    "HU - Aragorn Starter": "/gemp-lotr/images/boosters/hu_aragorn_starter.png",
    "HU - Mauhur Starter": "/gemp-lotr/images/boosters/hu_mauhur_starter.png",
    "HU - Booster": "/gemp-lotr/images/boosters/hu_booster.png",

    "RoS - Uruk Rampage Starter": "/gemp-lotr/images/boosters/ros_uruk_rampage_starter.png",
    "RoS - Evil Man Starter": "/gemp-lotr/images/boosters/ros_evil_man_starter.png",
    "RoS - Booster": "/gemp-lotr/images/boosters/ros_booster.png",

    "TaD - Faramir Starter": "/gemp-lotr/images/boosters/eof_faramir_starter.png",
    "TaD - Witch-king Starter": "/gemp-lotr/images/boosters/eof_witch_king_starter.png",
    "TaD - Booster": "/gemp-lotr/images/boosters/tad_booster.png",

    "REF - Booster": "/gemp-lotr/images/boosters/ref_booster.png",

    "Special-01": "/gemp-lotr/images/boosters/special-01.png",
    "Special-02": "/gemp-lotr/images/boosters/special-02.png",
    "Special-03": "/gemp-lotr/images/boosters/special-03.png",
    "Special-04": "/gemp-lotr/images/boosters/special-04.png",
    "Special-05": "/gemp-lotr/images/boosters/special-05.png",
    "Special-06": "/gemp-lotr/images/boosters/special-06.png",
    "Special-07": "/gemp-lotr/images/boosters/special-07.png",
    "Special-08": "/gemp-lotr/images/boosters/special-08.png",
    "Special-09": "/gemp-lotr/images/boosters/special-09.png",

    "(S)Special-1-3": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Special-4-6": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Special-7-9": "/gemp-lotr/images/boosters/starter_selection.png",

    "TSSealedS1D1": "/gemp-lotr/images/boosters/TSS1D1.png",
    "TSSealedS1D2": "/gemp-lotr/images/boosters/TSS1D2.png",
    "TSSealedS1D3": "/gemp-lotr/images/boosters/TSS1D3.png",
    "TSSealedS2D1": "/gemp-lotr/images/boosters/TSS2D1.png",
    "TSSealedS2D2": "/gemp-lotr/images/boosters/TSS2D2.png",
    "TSSealedS2D3": "/gemp-lotr/images/boosters/TSS2D3.png",
    "TSSealedS3D1": "/gemp-lotr/images/boosters/TSS3D1.png",
    "TSSealedS3D2": "/gemp-lotr/images/boosters/TSS3D2.png",
    "TSSealedS3D3": "/gemp-lotr/images/boosters/TSS3D3.png",

    "(S)TSSealed-S1": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)TSSealed-S2": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)TSSealed-S3": "/gemp-lotr/images/boosters/starter_selection.png",

    "Expanded": "/gemp-lotr/images/boosters/expanded.png",
    "Wraith": "/gemp-lotr/images/boosters/wraith.png",
    "AgesEnd": "/gemp-lotr/images/boosters/ages_end.png",
    
    "(S)FotR Block Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)TTT Block Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)RotK Block Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)SoG/MD Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)WotR Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)HU Block Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)Expanded Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",
    "(S)BR/HU/RoS Choice - Booster": "/gemp-lotr/images/boosters/booster_selection.png",

    "(S)Movie Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Reflections Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Hobbits Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Expanded Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Evil Characters Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)FotR Block Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)TTT Block Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)RotK Block Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)TS Special Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Movie Special Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)WotR Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)HU Block Choice - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    
    "(S)PC Promo Art Selection": "/gemp-lotr/images/boosters/pc_promo_selection.png",
    "(S)Masterwork Selection": "/gemp-lotr/images/boosters/masterwork_selection.png",
    
    
    "(S)SotP - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    
    "SotP - Tales & Weather Starter": "/gemp-lotr/images/boosters/V1-starter-tales_weather.png",
    "SotP - Aragorn Signet & Twilight Starter": "/gemp-lotr/images/boosters/V1-starter-aragorn_twilight.png",
    "SotP - Gandalf's Allies & Tentacles Starter": "/gemp-lotr/images/boosters/V1-starter-gandalf_tentacles.png",
    "SotP - Frodo Signet & Sauron Starter": "/gemp-lotr/images/boosters/V1-starter-frodo_sauron.png",
    
    "(R)SotP - Rare": "/gemp-lotr/images/boosters/V1-random-rare.png",
    "(R)SotP - Uncommon": "/gemp-lotr/images/boosters/V1-random-uncommon.png",
    "(R)SotP - Common": "/gemp-lotr/images/boosters/V1-random-common.png",
    
    "(S)SARU - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "SARU - Rohan & Dunland Starter": "/gemp-lotr/images/boosters/saru-rohan-dunland.png",
    "SARU - Dwarf & Evil Men Starter": "/gemp-lotr/images/boosters/saru-dwarf-men.png",
    "SARU - Gondor & Isengard Orc Starter": "/gemp-lotr/images/boosters/saru-gondor-isenorc.png",
    "SARU - Pipeweed & Isengard Uruk Starter": "/gemp-lotr/images/boosters/saru-pipeweed-isenuruks.png",
    "SARU - Smeagol & Urukhai Starter": "/gemp-lotr/images/boosters/saru-smeagol-uruks.png",
    
    "Event Chase Booster": "/gemp-lotr/images/boosters/event_award_booster.png",
    "Placement Random Chase Card Selector": "/gemp-lotr/images/boosters/event_high_placement.png",
    "Countdown to the King Collection": "/gemp-lotr/images/boosters/countdown_collection.png",
    "The Nine Riders Collection": "/gemp-lotr/images/boosters/nine_riders_collection.png",
    "(S)Alt Image Promo Selection": "/gemp-lotr/images/boosters/promo_selection.png",
    
    "Random Common Foil": "/gemp-lotr/images/boosters/random_foil.png",
    "Random Uncommon Foil": "/gemp-lotr/images/boosters/random_foil.png",
    "Random Rare Foil": "/gemp-lotr/images/boosters/random_foil.png",
    "Random Ultra Rare Foil": "/gemp-lotr/images/boosters/random_foil.png",
    
    "(S)SHELBI - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "SHELBI - Aragorn Starter":"/gemp-lotr/images/boosters/shelbi-aragorn.jpg",
    "SHELBI - Gandalf Starter":"/gemp-lotr/images/boosters/shelbi-gandalf.jpg",
    "SHELBI - Gimli Starter":"/gemp-lotr/images/boosters/shelbi-gimli.jpg",
    "SHELBI - Treebeard Starter":"/gemp-lotr/images/boosters/shelbi-treebeard.jpg",
    
    "2024 World Championship Invitation":"https://i.lotrtcgpc.net/other/2024-wc-invite.jpg",
    
    "Allies - Lothlorien Starter": "/gemp-lotr/images/boosters/gala_2025/allies_lothlorien.jpg",
    "Allies - Rivendell Starter": "/gemp-lotr/images/boosters/gala_2025/allies_rivendell.jpg",
    "Allies - Thrarin Starter": "/gemp-lotr/images/boosters/gala_2025/allies_thrarin.jpg",
    "Allies - Villagers Starter": "/gemp-lotr/images/boosters/gala_2025/allies_villagers.jpg",
    "Big Baddies - Gorbag's Command Starter": "/gemp-lotr/images/boosters/gala_2025/big-baddies_gorbag.jpg",
    "Big Baddies - Gothmog's Conquering Starter": "/gemp-lotr/images/boosters/gala_2025/big-baddies_gothmog.jpg",
    "Big Baddies - Sauron's Corruption Starter": "/gemp-lotr/images/boosters/gala_2025/big-baddies_sauron.jpg",
    "Big Baddies - Shelob's Web Starter": "/gemp-lotr/images/boosters/gala_2025/big-baddies_shelob.jpg",
    "Little Baddies - Bill Ferny's Ponies Starter": "/gemp-lotr/images/boosters/gala_2025/little-baddies_ferny.jpg",
    "Little Baddies - Gollum's Threat Starter": "/gemp-lotr/images/boosters/gala_2025/little-baddies_gollum.jpg",
    "Little Baddies - Grima's Assignment Starter": "/gemp-lotr/images/boosters/gala_2025/little-baddies_grima.jpg",
    "Little Baddies - Ted Sandyman's Control Starter": "/gemp-lotr/images/boosters/gala_2025/little-baddies_sandyman.jpg",
    "The Nine - Aragorn Starter": "/gemp-lotr/images/boosters/gala_2025/nine_aragorn.jpg",
    "The Nine - Boromir Starter": "/gemp-lotr/images/boosters/gala_2025/nine_boromir.jpg",
    "The Nine - Frodo Starter": "/gemp-lotr/images/boosters/gala_2025/nine_frodo.jpg",
    "The Nine - Gandalf Starter": "/gemp-lotr/images/boosters/gala_2025/nine_gandalf.jpg",
    "The Nine - Gimli Starter": "/gemp-lotr/images/boosters/gala_2025/nine_gimli.jpg",
    "The Nine - Legolas Starter": "/gemp-lotr/images/boosters/gala_2025/nine_legolas.jpg",
    "The Nine - Merry Starter": "/gemp-lotr/images/boosters/gala_2025/nine_merry.jpg",
    "The Nine - Pippin Starter": "/gemp-lotr/images/boosters/gala_2025/nine_pippin.jpg",
    "The Nine - Sam Starter": "/gemp-lotr/images/boosters/gala_2025/nine_same.jpg",
    "The Nine - Attea Starter": "/gemp-lotr/images/boosters/gala_2025/nine_attea.jpg",
    "The Nine - Cantea Starter": "/gemp-lotr/images/boosters/gala_2025/nine_cantea.jpg",
    "The Nine - Enquea Starter": "/gemp-lotr/images/boosters/gala_2025/nine_enquea.jpg",
    "The Nine - Lemenya Starter": "/gemp-lotr/images/boosters/gala_2025/nine_lemenya.jpg",
    "The Nine - Nelya Starter": "/gemp-lotr/images/boosters/gala_2025/nine_nelya.jpg",
    "The Nine - Nertea Starter": "/gemp-lotr/images/boosters/gala_2025/nine_nertea.jpg",
    "The Nine - Otsea Starter": "/gemp-lotr/images/boosters/gala_2025/nine_otsea.jpg",
    "The Nine - Toldea Starter": "/gemp-lotr/images/boosters/gala_2025/nine_toldea.jpg",
    "The Nine - Witch-King Starter": "/gemp-lotr/images/boosters/gala_2025/nine_twk.jpg",
    
    "(R)Movie Random": "/gemp-lotr/images/boosters/gala_2025/random-movie-booster.jpg",
    "(R)Expanded Random": "/gemp-lotr/images/boosters/gala_2025/random-expanded-booster.jpg",
    "(S)Ringbearer Choice": "/gemp-lotr/images/boosters/gala_2025/ring-bearer-selection.jpg",
    "(S)Ages End Choice": "/gemp-lotr/images/boosters/gala_2025/ages-end-selection.jpg",
    
    "(S)Allies - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Big Baddies - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)The Nine - Free Peoples Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)The Nine - Shadow Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(S)Little Baddies - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(R)FotR Block - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(R)TTT Block - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(R)RotK Block - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    "(R)WotR Block - Starter": "/gemp-lotr/images/boosters/starter_selection.png",
    
    "Fellowship Site Pack": "/gemp-lotr/images/boosters/gala_2025/fellowship-site-pack.jpg",
    "Towers Site Pack": "/gemp-lotr/images/boosters/gala_2025/towers-site-pack.jpg",
    "King Site Pack": "/gemp-lotr/images/boosters/gala_2025/king-site-pack.jpg",
    "WOTR Site Pack": "/gemp-lotr/images/boosters/gala_2025/wotr-site-pack.jpg",
    "Hunters Site Pack": "/gemp-lotr/images/boosters/gala_2025/hunters-site-pack.jpg"
    
};